name: Continuos integration

on: [push]

jobs:
  deploy:
    name: recreate docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.0      
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}      
          SLACK_COLOR: '#3278BD'
          SLACK_MESSAGE: 'Deploy completado con exito :rocket:'
          SLACK_TITLE: Deploy a producción
          SLACK_USERNAME: Github
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/Octocat.png?size=48
          # - name: deploy
          #   run: cd ~/Docker/carc-static && git pull
 
      - name: slack 2
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
        if: always() # Pick up events even if the job fails or is canceled. 

      - name: Slack Notification 3
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*Lint Check*'
          mention: 'here'
          mention_if: 'failure'
          channel: '#random'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
