name: Continuos integration

on: [push]

jobs:
  deploy:
    name: recreate docker image
    runs-on: self-hosted
    steps:
      - name: deploy
        run: cd ~/Docker/carc-static && git pull
 
 
 