name: Continuos integration

on: [push]

jobs:
  deploy:
    name: recreate docker image
    runs-on: ubuntu-latest
    steps:
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      - name: install ssh
        run: sudo apt-get install ssh -y
      - name: recreate image
        env:
          SSH_DEPLOY_SERVER: ${{ secrets.SSH_DEPLOY_SERVER }}
          SSH_DEPLOY_USER: ${{ secrets.SSH_DEPLOY_USER }}
        run: |
          ssh SSH_DEPLOY_USER@SSH_DEPLOY_SERVER "cd ~/Docker/carc-static && git pull && exit"
          ssh SSH_DEPLOY_USER@SSH_DEPLOY_SERVER "cd ~/Docker && ./deploy-carc.sh && exit"
       
