name: Continuos integration

on: [push]

jobs:
  deploy:
    name: recreate docker image
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v2
#      - name: Slack Notification
#        uses: rtCamp/action-slack-notify@v2.0.0      
#        env:
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}      
#          SLACK_COLOR: '#3278BD'
#          SLACK_MESSAGE: 'Deploy completado con exito :rocket:'
#          SLACK_TITLE: Notificación opcion 1
#          SLACK_USERNAME: Github
#          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/Octocat.png?size=48
          # - name: deploy
          #   run: cd ~/Docker/carc-static && git pull
 
#      - name: slack 2
#        uses: 8398a7/action-slack@v3
#        with:
#          status: ${{ job.status }}
#          fields: repo,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
#        if: always() # Pick up events even if the job fails or is canceled. 

      - name: Notify the start
        uses: innocarpe/actions-slack@v1
        with:
          status: ${{ job.status }}
          #success_text: '<!subteam^S1ABC2DEF> @${{ github.actor }} just started the workflow for `${{ github.ref }}`'
          success_text: '@${{ github.actor }} just started the pipeline for `${{ github.ref }}`, to see the progress click on Workflow'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # Required


      - name: Slack Notification 3
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*Status deploy:*'
          mention: 'here'
          mention_if: 'failure'
          url: ${{ secrets.SLACK_WEBHOOK }}
          channel: '#alertas'
          Commit: true
          username: Github_actions
          token: ${{ secrets.GITHUB_TOKEN }}      
